### ISSUE TITLE
Advanced Annotations

### ISSUE THREAD

**Issue by jjf28** [jjf28/RareCpp#37]
To unlock many potential powers within reflection: annotations need to be given more power.

First, annotations need to be capable of containing strings; not every annotation will need strings, so this should likely be a specialized kind of annotation. Two example uses:
- Change the name of the field in JSON without changing the field name in the struct nor writing customizers (which requires more advanced template techniques) for fields.
- Declare a URL (or portion of a URL) that results in a specific function call and myriad parameters and options

Annotations also need to be reasonable to write alongside the variable and function declarations, and if at all possible automatically pull in the annotations without explicitly placing them in the REFLECT macro. SFINAE may well provide a way of inspecting a structure to find the annotations.

Possible simple example:
```
struct Point
{
    NOTE(latitude) { Json::Name{"lat"} };
    double latitude;

    NOTE(longitude) { Json::Name{"long"} };
    double longitude;

    REFLECT(() Point, latitude, longitude)
};
```

Possible involved example:
```
struct State
{
    int value;
    long otherValue;

    NOTE(status) { std::tuple {
        Json::Name{"code"},
        Json::EnumInt{}
    } };
    Status status;

    NOTE(update) { Rest::Endpoint {
        Rest::Method::PATCH,
        Rest::Url{"/update/{value}/{otherValue}"},
        Rest::Param<int>{"value"},
        Rest::Param<long>{"otherValue"}
    } };
    auto update(int value, long otherValue) {
        this->value = value;
        this->otherValue = otherValue;
        this->status = Status::Cached;
        return Json::out(*this);
    }

    REFLECT(() State, value, otherValue, update, status)
};```

**Comment by jjf28** [comment]
NOTE could be as simple as
```
#define NOTE(field) static constexpr auto field##_
```

REFLECT would then have the work of finding whether each field had a note, and staging it, consequently the NOTE types must live in constexpr land - which should be doable with string_views and such.

**Comment by jjf28** [comment]
I spent two days on the problem and finally confirmed that there is no way to pull something defined just before a struct as a reference inside the struct, and pull a reference to a default value if not present.

Using partial template specialization was ruled out as template specializations cannot be declared outside their original namespace. Sfinae was ruled out as there is no way to get an alias to the enclosing struct and/or namespace (possibly the global namespace).

A mix of function overloading and sfinae came closest, as it was possible to get sfinae to prefer picking the annotation if present, and picking the default overload otherwise...

```
inline namespace
{
    static constexpr auto getNote(uint, uint) { return std::tuple<>{}; }
}

/* May be commented out */ struct i_type {};
/* May be commented out */ static constexpr i_type getNote(uint, int) { return i_type{}; }
struct i
{
    static constexpr auto note = getNote(0, 0);
    using T = decltype(note);
};
struct j
{
    static constexpr auto note = getNote(0, 0);
    using T = decltype(note);
};

struct k_type {};
static constexpr k_type getNote(int, int) { return k_type{}; }
struct k
{
    static constexpr auto note = getNote(0, 0);
    using T = decltype(note);
};

....

    std::cout << TypeToStr<i::T>() << std::endl;
    std::cout << TypeToStr<j::T>() << std::endl;
    std::cout << TypeToStr<k::T>() << std::endl;
```

However, when multiple structs in the same scope have annotations, there's no way to get sfinae to prefer the default over the annotation for the previous struct, and there's nothing to explicitly specialize on that the struct would know about (we can declare a type, but that just pushes the problem back to identifying that type, which has the same issues) unless we always require a forward declaration of the struct, which with templates and such is of course, harder than simply changing REFLECT to REFLECT_NOTED and ergo not a solution I'm entertaining.

**Comment by jjf28** [comment]
As of https://github.com/jjf28/RareCpp/commit/e5123e74883242ed8876a7c40570c8762a2c6688 advanced annotations are fully implemented; after full testing of changes related to the removal of the Reflected annotation (which previously made checking if a type is reflected field dependent, and not usable on any but the rightmost/most deeply nested value) and associated upgrades to json representation/possible inputs... I need to add the JsonName annotation into the Json code

**Comment by jjf28** [comment]
Identified a possible hope for unifying the REFLECT and REFLECT_NOTED macros, by essentially forcing the compiler to scan for function overloads line-by-line in the file https://godbolt.org/z/T5borY

**Comment by jjf28** [comment]
I worked the thread much further till a dead end: inheritance kills all hope of unification via line scanning+ADL - when you inherit from something with annotations you take in a version of cl which hides the class-level annotation's cl (which is necessarily in the next-namespace up and thus of lower priority than inherited functions), thus killing your ability to automatically detect the existence of a class-level annotation at compile time for inherited functions.

In addition to problem of inheritance hiding the detectable function this solution was very complex, likely to heavily impact compile times, restrict what client code was allowed to do with respect to reflecting nested classes in fairly arbitrary ways, and add heavily to namespace pollution; ergo I'm calling this dead once more.

At the time of writing you can still access the code here: https://github.com/jjf28/RareCpp/tree/postmortem/unify-macros

**Comment by TheNitesWhoSay** [comment]
Macro unification should actually be solvable with inline friends https://godbolt.org/z/WYbed7GnK

They're a bit of a cheat that's perfect for this situation: friend functions belong to the enclosing namespace (kinda) not to the class so you can overload functions and prefer the version of a function outside the class. This doesn't solve everything (e.g. same class name in different namespaces leads to ambiguity which I'm finding tricky to work around), but puts it back in the realm of possibility.

**Comment by TheNitesWhoSay** [comment]
this solution appears to be viable for solving the same class in different namespaces problem: https://godbolt.org/z/o874xqGWd
